### ISSUE TITLE
Planeación Dashboard de ventas

### ISSUE THREAD

**Issue by CesarAscencioV** [prestemos/planning#112]

**Comment by MexicanGodzilla** [comment]
Bocetos de primeros módulos para la sesión de design critique
![Uploading Primeros bocetos.png…]()

**Comment by MexicanGodzilla** [comment]
Bocetos para organización de todos los módulos del dashboard
![Propuesta Dashboard](https://user-images.githubusercontent.com/51377746/153950442-89d738fc-3c48-4563-a658-dfe9362a6ce3.png)

**Comment by MexicanGodzilla** [comment]
Bocetos de primeros módulos para la sesión de design critique
![Primeros bocetos](https://user-images.githubusercontent.com/51377746/153950696-ebc62c77-018d-4974-b5e7-c1f11f3d1e40.png)
