### ISSUE TITLE
Revisión y mejoras parte 1 dashboard ventas

### ISSUE THREAD

**Issue by CesarAscencioV** [prestemos/planning#127]
- [ ] Revisar con Antonio primeros avances del dashboard: visualización, reportes, fiabilidad.
- [ ] Hacer wireframes de módulos restantes del dashboard: cierres, historial cierres, info cierres, seguimiento regional, recurrencia regional, información de agencias.
- [ ] Hablar con Cindy e Itzel acerca de la fiabilidad del uso de pagos iniciales.
- [ ] Presentar wireframes en design critique y anotar cambios.
- [ ] Hablar con Paloma, Alberto, Georgette y Adrián acerca del contexto de uso del dashboard.
- [ ] Hacer propuesta de layout y vistas de detalle para acomodar ahí los mockups de los módulos.

**Comment by MexicanGodzilla** [comment]
Prototipo de la propuesta de layout para el dashboard de ventas: https://www.sketch.com/s/b9aa0241-e667-443d-9575-946bca9570a7/a/wLlOen9/play
