### ISSUE TITLE
Wireframes de primeros cuatro documentos

### ISSUE THREAD

**Issue by CesarAscencioV** [prestemos/planning#207]
- [x] Pantalla de carga del EP y bandeja de OC
- [x] Factura original
- [x] Refacturaciones y endosos
- [x] REPUVE
- [x] Tenencias (este tal vez no lo termine porque está medio complejo)

Buscar VoBo. de Eduardo Pedro, Mike y Remo

**Comment by MexicanGodzilla** [comment]
Enlace del prototipo de los wireframes de los primeros 4 documentos: https://www.sketch.com/s/deb4ee46-b24d-472f-8026-d8fb4aed70cb/a/Jngd135/play
