### ISSUE TITLE
Arreglar Data Clip Online Offline

### ISSUE THREAD

**Issue by CesarAscencioV** [prestemos/planning#463]
### Objetivo

Arreglar data Clip para obtener información de online-offline

### Alcance

Ayudar a Marina a corregir data clip existente de online offline para que no truene

### Stakeholders

Producto - Marina

### Definition of Done

Vobo. Marina

**Comment by alejogtz** [comment]
![image](https://user-images.githubusercontent.com/36853149/186003304-55b13789-4e73-4e03-bff1-2af3723036aa.png)
