### ISSUE TITLE
Agregar nuevo/seminuevo estado de emplacamiento Front

### ISSUE THREAD

**Issue by CesarAscencioV** [prestemos/planning#580]
### Problema a resolver

No se distingue el tipo de vehículo (nuevo/seminuevo) en el proceso de elección de entidad de emplacamiento, haciendo que la información llegue a ser confusa.

Los clientes de ciertos estados solo pueden emplacar en ese estado por cuestiones de impuestos y riesgo para Nexu.

### Objetivo

Actualizar vistas relacionadas a entidad de emplacamiento y limitar las opciones según el cliente

### Alcance

Actualizar vista de diálogo de elección de entidad de emplacamiento
Actualizar vista de configuración de precios de estado de emplacamiento

### Stakeholders

@remigioamc 
@CesarAscencioV 

### Definition of Done

Release to prod

**Comment by alejogtz** [comment]
Duda: Estas vistas entran en el scope de la tarea? o pertenecen a otro proceso?

![Image](https://user-images.githubusercontent.com/36853149/204348436-7631ab8c-2d2c-43a3-9133-c6652696abad.png)
