### ISSUE TITLE
Wireframes para Proceso de Entregas

### ISSUE THREAD

**Issue by CesarAscencioV** [prestemos/planning#68]
![Flujo_Entregas](https://user-images.githubusercontent.com/51377746/147971760-1eb4a72b-78c6-4bda-9063-f386f35febe0.jpg)
Pasar los bocetos iniciales de la propuesta para el flujo de entregas (cuadros morados) a wireframes.
- [x] Hacer wireframes V1.0 tomando como base los bocetos iniciales.
- [x] Revisar wireframes con Arthur y Remo, compartirlos a Miguel y Antonio para VoBo/Cambios.
- [x] Modificar wireframes con los comentarios de las revisiones.
- [x] Revisión de wireframes v2.0 con Arthur y Remo, y volver a compartirlos a Miguel y Antonio para Vobo/Cambios.
- [x] Hacer versión final de wireframes en limpio con VoBo de Arthur, Remo, Miguel y Antonio para empezar mockups.

**Comment by MexicanGodzilla** [comment]
- Wireframes v1.0: https://www.sketch.com/s/9ed502d2-0175-4932-87a7-92e049f58be9/a/WKq9L2n/play
- Wireframes v2.0: https://www.sketch.com/s/9ed502d2-0175-4932-87a7-92e049f58be9/a/GmrLqyL/play
- Wireframes v3.0: https://www.sketch.com/s/9ed502d2-0175-4932-87a7-92e049f58be9/a/Gmr1kow/play
