### ISSUE TITLE
Mockups Proceso de Entregas

### ISSUE THREAD

**Issue by CesarAscencioV** [prestemos/planning#69]
Convertir los wireframes a mockups para el proceso de Entrega>Resguardo.
- [x] Hacer mockups V1.0 tomando como base los wireframes v3.0.
- [x] Revisar mockups con Arthur y Remo, compartirlos a Miguel y Antonio para VoBo/Cambios.
- [x] Hacer mockups V2.0 tomando en cuenta los comentarios de Arthur, Remo y Miguel.
- [x] Revisar mockups con Arthur y Remo, compartirlos a Miguel para VoBo/Cambios.
- [x] Hacer mockups V3.0 tomando en cuenta los comentarios de Arthur, Remo y Miguel.
- [x] Revisar mockups y nuevo flujo con Arthur y Remo, compartirlos a Miguel para VoBo/Cambios.

**Comment by MexicanGodzilla** [comment]
- Mockups/prototipo v1.0: https://www.sketch.com/s/9ed502d2-0175-4932-87a7-92e049f58be9/a/oYRMlqY/play
- Mockups/prototipo v2.0: https://www.sketch.com/s/9ed502d2-0175-4932-87a7-92e049f58be9/a/9PGoW1n/play
