### ISSUE TITLE
Pruebas OCR de comprobantes de domicilio

### ISSUE THREAD

**Issue by CesarAscencioV** [prestemos/planning#805]
**Contexto**

El proceso actual de registro y análisis de comprobantes de domicilio para Telmex, Telcel, IZZI y Totalplay (Recibo y factura) se hace de manera manual. 

Para el proyecto de 10 minutos, tenemos un 30% de la clientes actualmente que entregan una de estos 5 documentos, por lo que queremos automatizar lo más posible el flujo de análisis.

**Problemática**

Todos los procesos de registro y validación de candados de seguridad de estos documentos se hacen de manera manual, lo cual genera tiempos de análisis de validación de comprobante de domicilio que sobrepasan los 10 minutos y nos impiden automatizar el flujo de análisis.

**Objetivos**

1. Identificar la información entrega Nubarium por cada uno de estos documentos
2. Identificar que candados de seguridad podemos validar automáticamente  con el proveedor de OCR
3. Definir Inputs necesarios para cotejo de candados de seguridad

**Solución** 

1. Lista de candados de seguridad que se pueden hacer de manera automática con el OCR del proveedor
2. Inputs necesarios para los que no se pueden hacer por el proveedor

**Recursos**

Candados de seguridad

[[Candados de seguridad de comprobantes de domicilio-fer.pdf (1).pptx](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/9d30fc8d-bef5-4623-bfb8-0e26e4be3f12/Candados_de_seguridad_de_comprobantes_de_domicilio-fer.pdf_(1).pptx)](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/9d30fc8d-bef5-4623-bfb8-0e26e4be3f12/Candados_de_seguridad_de_comprobantes_de_domicilio-fer.pdf_(1).pptx)

**Stakeholders**

Simon
Remigio

**Comment by Simonexu** [comment]
Lista de candados de seguridad: https://docs.google.com/spreadsheets/d/1aay1Hi2WQDBCOKk0OVAlIlx19e6PytnbYV8Y4TsFCzU/edit#gid=0

CFE | 8049 | 68%
-- | -- | --
GAS AMICSA | 46 | 0%
Gas Naturgy | 117 | 1%
**IZZI** | 835 | 7%
**Megacable** | 197 | 2%
**TELMEX** | 1660 | 14%
**TotalPlay (Factura)** | 145 | 1%
**TotalPlay (Recibo)** | 709 | 6%
Grand Total | 11758 | 100%
