### ISSUE TITLE
Primeros Mockups parte 1 dashboard ventas

### ISSUE THREAD

**Issue by remigioamc** [prestemos/planning#84]
- [ ] Revisar con Antonio necesidades de visualización y reportes para gerentes y subdirector.
- [x] Definir con qué módulos del dashboard empezar.
- [x] Hacer cambios y empezar mockups con los comentarios que salieron en la design critique.
- [x] Aclarar con Antonio dudas sobre la revisión de metas de gerentes.
- [x] Tener lista la primera propuesta de mockups para: registro y aprobación de metas, métricas (funnel), actualizaciones, agencias, y recurrencia.

**Comment by MexicanGodzilla** [comment]
Enlace al archivo con los primeros mockups para el dashboard de ventas y el flujo de registrar metas: https://www.sketch.com/s/b9aa0241-e667-443d-9575-946bca9570a7
