### ISSUE TITLE
Vobo y ajuste de proceso de entrega

### ISSUE THREAD

**Issue by CesarAscencioV** [prestemos/planning#98]
- [x] Llamada con Miguel para mostrarle el prototipo t recoger nuevas dudas o cambios.
- [x] Hacer nuevo diagrama de flujo de ambos procesos con los cambios del demo y de Miguel.
- [x] Acomodar las pantallas y corregir wordings para que la validación la haga Ops.
- [x] Diseñar 2 nuevas pantallas para un dashboard donde estén las entregas pendientes y las completadas.
- [x] Revisión del nuevo prototipo con Arthur y Remo.
- [x] Cambios en las pantallas con los comentarios de la revisión.
- [x] Revisar con Miguel, Axell, y Fer Díaz el nuevo prototipo ya con todos los cambios.
- [x] Subir las nuevas pantallas del proceso de Entregas>Resguardo a Zeplin.

**Comment by MexicanGodzilla** [comment]
Enlace del último prototipo: https://www.sketch.com/s/9ed502d2-0175-4932-87a7-92e049f58be9/a/DP1Wk7e/play

**Comment by MexicanGodzilla** [comment]
Enlace de las pantallas en Zeplin: https://zpl.io/299rj1e
